### ISSUE TITLE
how can I get the original tweets?

### ISSUE THREAD

**Issue by csorg** [medeffects/tweet_corpora#2]
the medication corpus file only have tweet ID and annotation(is PET), no user ID,how can I get the related tweets?

**Comment by medeffects** [comment]
on the same page, there is a link to a code snip from another group. you could try to use the code to retrieve the tweets. we have never tested the code with our tweet ids.



btw, twitter does not allow anyone to redistribute its data...



hope this helps.

________________________________

**Comment by csorg** [comment]
ok,thanks
